### ISSUE TITLE
[util/BloomFilter] java.lang.IndexOutOfBoundsException: bitIndex < 0: -392407046

### ISSUE THREAD

**Issue by doflink** [scalanlp/breeze#632]
java.lang.IndexOutOfBoundsException: bitIndex < 0: -392407046
       	at java.util.BitSet.get(BitSet.java:615)
       	at breeze.util.BloomFilter.apply(BloomFilter.scala:40)
       	at breeze.util.BloomFilter.contains(BloomFilter.scala:46)

I got the error, when I use `BloomFilter.optimallySized[String]` to filter out 6103515625 data items `(activeBuckets(o).forall(i => bits.get(i)))`. The reason seems like it is greater than the max integer. Should breeze bloom filter support `numBuckets: Long` instead of `numBuckets: Int`?

**Comment by rs-doi** [comment]
I am getting a similar error when adding items to the filter.

> java.lang.IndexOutOfBoundsException: bitIndex < 0: -134621384
> 	at java.util.BitSet.set(BitSet.java:444)
> 	at breeze.util.BloomFilter.$plus$eq(BloomFilter.scala:67)

I can't see the bug though.  There's an `abs` call on the hash function so the index should be `positive_integer % another_positive_integer`, which looks to me like it should always return a positive integer.

**Comment by dlwh** [comment]
i fixed this a while back and forgot to close the issue

**Comment by kdsandip** [comment]
I am still getting the same issue in the latest released build 1.0-RC2
as well the bloomfilter class resembles the same

```
class BloomFilter[@specialized(Int, Long) T](val numBuckets: Int, val numHashFunctions: Int, val bits: util.BitSet)
    extends (T => Boolean)
    with Serializable {
def this(**numBuckets: Int**, numHashFunctions: Int) = this(numBuckets, numHashFunctions, new util.BitSet(numBuckets))
```
